kube-prometheus-stack:
  alertmanager:
    config:
      global:
        # Alerts without an end timeout after 5 minutes
        resolve_timeout: 5m

        # SMTP configuration
        smtp_smarthost: "smtp.smtp:25"
        smtp_hello: "alertmanager.cluster-home.johnson.computer"
        smtp_from: "Alert Manager <alertmanager@johnson.computer>"
        smtp_require_tls: false

      inhibit_rules:
        - source_matchers:
            - "severity = critical"
          target_matchers:
            - "severity =~ warning|info"
          equal:
            - "namespace"
            - "alertname"
        - source_matchers:
            - "severity = warning"
          target_matchers:
            - "severity = info"
          equal:
            - "namespace"
            - "alertname"
        - source_matchers:
            - "alertname = InfoInhibitor"
          target_matchers:
            - "severity = info"
          equal:
            - "namespace"

      route:
        group_by: ["namespace"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: "null"
        routes:
          - receiver: "null"
            matchers:
              - alertname =~ "InfoInhibitor|Watchdog"
          - receiver: "mj-sms"
            matchers:
              - severity =~ "critical"
            continue: true
          - receiver: "mj-email"
            continue: true

      receivers:
        - name: "mj-email"
          email_configs:
            - send_resolved: true
              to: "Mike Johnson <michael@johnson.gg>"
        - name: "mj-sms"
          email_configs:
            - send_resolved: true
              to: "6788358132@tmomail.net"
              headers:
                Subject: '{{ template "pushover.default.title" . }}'
              text: '{{ template "pushover.default.message" . }}'
              html: ""
        - name: "null"

  grafana:
    adminPassword: null
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Grafana
        hajimari.io/icon: chart-bar

        # only allow internal clients
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
      hosts:
        - &host grafana.johnson.computer
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
      - name: Alertmanager
        type: alertmanager
        url: http://alertmanager-operated:9093
        jsonData:
          implementation: prometheus
    envFromSecret: grafana-secrets
    grafana.ini:
      server:
        root_url: https://grafana.johnson.computer
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        name: Dex
        client_id: grafana-sso
        client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
        scopes: openid profile email groups
        auth_url: https://dex.johnson.computer/auth
        token_url: https://dex.johnson.computer/token
        api_url: https://dex.johnson.computer/userinfo
    persistence:
      enabled: true
    # this deployment strategy is necessary because of persistence
    deploymentStrategy:
      type: Recreate

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
