cilium:
  cluster:
    name: home
    id: 1

  rollOutCiliumPods: true

  # only use correct interface
  devices: servers

  # enable fair queueing
  bandwidthManager: true
  kubeProxyReplacement: strict

  # disable conntrack rules for performance
  installNoConntrackIptablesRules: true
  tunnel: disabled
  autoDirectNodeRoutes: true
  ipv4NativeRoutingCIDR: "10.42.0.0/16"

  bpf:
    masquerade: true

  containerRuntime:
    integration: containerd

  externalIPs:
    enabled: true

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
      clusterPoolIPv4MaskSize: 24

  hubble:
    ui:
      enabled: true

      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/appName: Hubble
          hajimari.io/icon: telescope

          kubernetes.io/ingress.class: nginx

          # only allow internal clients
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
        hosts:
          - &hubble_host hubble.johnson.computer
        tls:
          - secretName: hubble-tls-certificate
            hosts:
              - *hubble_host
    relay:
      enabled: true

  operator:
    rollOutPods: true

  bgp:
    enabled: true
    announce:
      loadbalancerIP: true
      # advertising pod CIDR is broken until v1.12
      # podCIDR: true
