cilium:
  cluster:
    name: home
    id: 1

  rollOutCiliumPods: true

  autoDirectNodeRoutes: true
  tunnel: disabled

  containerRuntime:
    integration: containerd

  externalIPs:
    enabled: true

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: ["10.72.0.0/16"]
      clusterPoolIPv4MaskSize: 20

  operator:
    rollOutPods: true

    # because we only have 1 node, allow operator pods to be on the same node
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []

  bgp:
    enabled: false
    announce:
      loadbalancerIP: true
