cert-manager:
  # bypass our split-horizon DNS
  podDnsPolicy: "None"
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
      - "1.0.0.1"

  installCRDs: true

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

accessKeyID: AKIARJTSQTR3JRTGU2XY

issuer:
  email: michael@johnson.gg
