- name: Install smartmontools package
  ansible.builtin.yum:
    name: smartmontools
    state: present
  notify:
    - Restart smartd

- name: Copy smartd configuration
  ansible.builtin.copy:
    src: smartd.conf
    dest: /etc/smartmontools/smartd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart smartd

- name: Enable smartd
  ansible.builtin.systemd:
    name: smartd
    enabled: true
