external-dns:
  provider: aws
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: route53-access-key
          key: access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: route53-access-key
          key: secret-access-key
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)

  # fix CNAME records
  txtPrefix: "_k8s-meta-"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
