apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: shared-cluster
spec:
  teamId: "shared"
  volume:
    size: 8Gi
    storageClass: zfs-postgresql
  numberOfInstances: 2
  users:
    michael-admin:  # database owner
    - superuser
    - createdb
    synapse: []
  databases:
    synapse: matrix.synapse
  postgresql:
    version: "14"
