apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: shared-cluster
spec:
  teamId: "shared"
  volume:
    size: 8Gi
    storageClass: zfs-postgresql
  numberOfInstances: 2
  users:
    michael-admin:  # database owner
    - superuser
    - createdb
    matrix.synapse: []
    matrix.mautrix-whatsapp: []
    authentik.authentik: []
  databases:
    synapse: matrix.synapse
    mautrix-whatsapp: matrix.mautrix-whatsapp
    authentik: authentik.authentik
  postgresql:
    version: "14"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: shared-cluster-vacuum-lite
spec:
  schedule: "15 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: vacuum-lite
              image: postgres:14.2
              imagePullPolicy: IfNotPresent
              env:
                - name: PG_COLOR
                  value: always
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres.shared-cluster.credentials.postgresql.acid.zalan.do
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres.shared-cluster.credentials.postgresql.acid.zalan.do
                      key: password
              command: ["/usr/bin/vacuumdb", "--verbose", "--parallel=4", "--all", "--analyze", "--host=shared-cluster.postgresql.svc.cluster.local"]
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: shared-cluster-vacuum-full-matrix
spec:
  schedule: "45 4 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: vacuum-full-matrix
              image: postgres:14.2
              imagePullPolicy: IfNotPresent
              env:
                - name: PG_COLOR
                  value: always
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres.shared-cluster.credentials.postgresql.acid.zalan.do
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres.shared-cluster.credentials.postgresql.acid.zalan.do
                      key: password
              command: ["/usr/bin/vacuumdb", "--verbose", "--full", "--analyze", "--host=shared-cluster.postgresql.svc.cluster.local", "synapse"]
          restartPolicy: Never
