descheduler:
  deschedulerPolicy:
    evictLocalStoragePods: true

    strategies:
      RemoveDuplicates:
        enabled: false
        nodeFit: true
      RemovePodsViolatingNodeTaints:
        enabled: true
        nodeFit: true
      RemovePodsViolatingNodeAffinity:
        enabled: true
        nodeFit: true
        params:
          nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
      RemovePodsViolatingInterPodAntiAffinity:
        enabled: true
      LowNodeUtilization:
        enabled: true
        nodeFit: true
