paperless:
  env:
    PAPERLESS_REDIS: redis://paperless-redis-master
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document

        # only allow internal clients
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
      hosts:
        - host: &host paperless.johnson.computer
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-tls-certificate
          hosts:
            - *host
  postgresql:
    enabled: true
    persistence:
      enabled: true
      storageClass: zfs-postgresql
  redis:
    enabled: true
    architecture: standalone
    persistence:
      enabled: true
      storageClass: zfs-postgresql
