metal:
  children:
    masters:
      hosts:
        hv01:
          {
            ansible_host: 10.0.2.10,
            mac: "50:9a:4c:60:59:e7",
            disk: sda,
            network_interface: eno1,
          }
    workers:
      hosts: []
