metal:
  children:
    masters:
      hosts:
        hv01-home.johnson.computer:
          ansible_host: 10.0.2.10
          disk: disk/by-id/ata-Samsung_SSD_860_EVO_2TB_S597NZFNA02430M
          network:
            mac: "50:9a:4c:60:59:e7"
            bond_members: ["eno1", "eno2"]
            gateway: 10.0.2.1
            netmask: 255.255.255.0
        hv02.home.johnson.computer:
          ansible_host: 10.0.2.11
          disk: disk/by-path/pci-0000:05:00.0-nvme-1
          network:
            mac: "44:a8:42:2d:f5:b5"
            bond_members: ["eno1", "eno2", "eno3", "eno4"]
            gateway: 10.0.2.1
            netmask: 255.255.255.0
