apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager-servicemonitor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      operated-alertmanager: 'true'
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: '9093'
    path: /metrics
