apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeserver-keys
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: homeserver-keys
  data:
    # Connectors
    - secretKey: matrix_key.pem
      remoteRef:
        key: /matrix/keys
        property: latest
