apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeserver-keys
  namespace: { { .Release.Namespace } }
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: homeserver-keys
  data:
    - secretKey: signing-key
      remoteRef:
        key: /matrix/keys
        property: signing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeserver-extra-secrets
  namespace: { { .Release.Namespace } }
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: extra-secret-config
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: homeserver-extra-config
            items:
              - key: config.yaml
  data:
    - secretKey: impersonation_secret
      remoteRef:
        key: /matrix/appservice/impersonation
        property: shared_secret
    - secretKey: macaroon
      remoteRef:
        key: /matrix/keys
        property: macaroon
    - secretKey: pepper
      remoteRef:
        key: /matrix/keys
        property: password-pepper
    - secretKey: registration_secret
      remoteRef:
        key: /matrix/keys
        property: registration-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeserver-extra-config
data:
  config.yaml: |
    modules:
      - module: shared_secret_authenticator.SharedSecretAuthProvider
        config:
          shared_secret: {{ `{{ .impersonation_secret | quote }}` }}

          # By default, only login requests of type `com.devture.shared_secret_auth` are supported.
          # Below, we explicitly enable support for the old `m.login.password` login type,
          # which was used in v1 of matrix-synapse-shared-secret-auth and still widely supported by external software.
          # If you don't need such legacy support, consider setting this to `false` or omitting it entirely.
          m_login_password_support_enabled: true

          # By default, only login requests of type `com.devture.shared_secret_auth` are supported.
          # Advertising support for such an authentication type causes a problem with Element, however.
          # See: https://github.com/vector-im/element-web/issues/19605
          #
          # Uncomment the line below to disable `com.devture.shared_secret_auth` support.
          # You will then need to:
          # - have `m_login_password_support_enabled: true` to enable the `m.login.password` login type
          # - authenticate using `m.login.password` requests, instead of ``com.devture.shared_secret_auth` requests
          # com_devture_shared_secret_auth_support_enabled: false

    macaroon_secret_key: {{ `{{ .macaroon | quote }}` }}

    registration_shared_secret: {{ `{{ .registration_secret | quote }}` }}

    password_config:
      pepper: {{ `{{ .pepper | quote }}` }}
