apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeserver-keys
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: homeserver-keys
  data:
    - secretKey: signing-key
      remoteRef:
        key: /matrix/keys
        property: signing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeserver-extra-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: extra-secret-config
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: homeserver-extra-config
            items:
              - key: config.yaml
  data:
    - secretKey: macaroon
      remoteRef:
        key: /matrix/keys
        property: macaroon
    - secretKey: pepper
      remoteRef:
        key: /matrix/keys
        property: password-pepper
    - secretKey: registration_secret
      remoteRef:
        key: /matrix/keys
        property: registration-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeserver-extra-config
data:
  config.yaml: |
    macaroon_secret_key: {{ `{{ .macaroon | quote }}` }}
    registration_shared_secret: {{ `{{ .registration_secret | quote }}` }}

    password_config:
      pepper: {{ `{{ .pepper | quote }}` }}
