apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dendrite
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: dendrite
      component: monolight
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: 'web'
    path: /metrics
