apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  fstype: "zfs"
  poolname: "tank/kubernetes"
  shared: "yes"
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - hv01-home.johnson.computer
