kube-ops-view:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Ops View
        hajimari.io/icon: view-dashboard

        # only allow internal clients
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
      hosts:
        - host: &host ops-dashboard.johnson.computer
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kube-ops-view-tls-certificate
          hosts:
            - *host
