dex:
  config:
    issuer: https://dex.johnson.computer
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: gitea
        id: gitea
        name: Gitea
        config:
          clientID: $GITEA_CLIENT_ID
          clientSecret: $GITEA_CLIENT_SECRET
          redirectURI: https://dex.johnson.computer/callback
          baseURL: https://git.johnson.computer
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - "https://grafana.johnson.computer/login/generic_oauth"
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: "false"
    hosts:
      - host: &host dex.johnson.computer
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-tls-certificate
        hosts:
          - *host
