trow:
  trow:
    domain: registry.johnson.computer
    # user: user
    # password: password
    validation:
      enabled: false
      allowDocker: false
      allowKubernetes: true
      allowPrefixes: []
      allowImages: []
      disallowLocalPrefixes: []
      disallowLocalImages: []
      proxyDockerHub: false

  ingress:
    enabled: false # TODO https://github.com/ContainerSolutions/trow/issues/282
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hajimari.io/enable: "false"

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 108.211.229.1/32
    hosts:
      - host: &host registry.johnson.computer
        paths:
          - /
    tls:
      - secretName: trow-tls-certificate
        hosts:
          - *host
  volumeClaim:
    storageClassName: zfs-default
