gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 108.211.229.1/32
    hosts:
      - host: &host git.johnson.computer
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host

  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.johnson.computer

      mailer:
        ENABLED: "true"
        FROM: "Gitea <git@johnson.computer>"
        MAILER_TYPE: smtp
        HOST: "smtp.smtp:25"
        IS_TLS_ENABLED: "false"

  service:
    ssh:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 138.197.49.96

  persistence:
    storageClass: zfs-default
  postgresql:
    persistence:
      storageClass: do-block-storage
