gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    hosts:
      - host: &host git.johnson.computer
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret:
      username:
      password:
      email:
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.johnson.computer
  persistence:
    storageClass: zfs-default
  postgresql:
    persistence:
      storageClass: zfs-postgresql
