renovate:
  cronjob:
    schedule: "29 * * * *"
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.johnson.computer/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true
      }
  existingSecret: renovate-secret
