renovate:
  cronjob:
    schedule: "0 9 * * 6" # At 09:00 every month
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.johnson.computer/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true
      }
  existingSecret: renovate-secret
