apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-credentials
  namespace: k8up-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: backblaze-credentials
  data:
    - secretKey: application-key-id
      remoteRef:
        key: /k8up/backblaze-credentials
        property: application-key-id
    - secretKey: application-key
      remoteRef:
        key: /k8up/backblaze-credentials
        property: application-key
    - secretKey: repo-password
      remoteRef:
        key: /k8up/backblaze-credentials
        property: repo-password
