- name: Download ZFS release RPM
  ansible.builtin.get_url:
    url: "{{ rpm_url }}"
    dest: "/tmp/{{ rpm_url | basename }}"
    checksum: "{{ rpm_checksum }}"
    mode: 0644
  register: rpm

- name: Importing OpenZFS GPG key
  ansible.builtin.rpm_key:
    state: present
    fingerprint: C93A FFFD 9F3F 7B03 C310 CEB6 A9D5 A1C0 F14A B620
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc93afffd9f3f7b03c310ceb6a9d5a1c0f14ab620

- name: Install ZFS release package
  yum:
    name: "{{ rpm.dest }}"
    state: present

- name: Enable EPEL
  yum:
    name: epel-release
    state: present

- name: Install kernel development package
  yum:
    name: kernel-devel
    state: present

- name: Install ZFS package
  yum:
    name: zfs
    state: present

- name: Load ZFS kernel module
  community.general.modprobe:
    name: zfs
    state: present

- name: Create directory to store ZFS encryption keys
  ansible.builtin.file:
    path: /etc/zfs-keys
    state: directory
    mode: 0700

- name: Copy tank key to node
  ansible.builtin.copy:
    src: tank-key
    dest: /etc/zfs-keys/tank
    owner: root
    group: root
    mode: 0400

- name: Activate ZFS pool
  ansible.builtin.command: /usr/sbin/zpool import tank
  register: result
  changed_when: "result.rc == 0"
  failed_when: 'result.rc != 0 and "a pool with that name already exists" not in result.stderr'

- name: Cache ZFS pool
  ansible.builtin.command: /usr/sbin/zpool set cachefile=/etc/zfs/zpool.cache tank
  changed_when: False

- name: Unlock ZFS pool
  ansible.builtin.command: /usr/sbin/zfs load-key -r tank
  register: result
  changed_when: '"successfully loaded" in result.stdout'
  failed_when: '"Key load error" in result.stderr'

- name: Mount ZFS volumes
  ansible.builtin.command: /usr/sbin/zfs mount -a
  changed_when: False
