apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
data:
  config.yaml: |
    peers:
      - peer-address: 10.0.2.1
        peer-asn: 64521
        my-asn: 64521
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 76.234.108.200/29
