apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
      route53:
        region: us-east-1
        accessKeyID: {{ .Values.accessKeyID }}
        secretAccessKeySecretRef:
          name: route53-access-key
          key: secret-access-key
