# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true
# TODO create tokens and put to Vault automatically
# - gitea/renovate:
#   - id
#   - token
# - gitea/dex:
#   - client_id
#   - client_secret
# TODO import to vault?
# - metal/ssh:
#   - private_key  # needs ending new line https://github.com/ansible/awx/issues/9082
# - external/terraform-cloud:
#   - token
# - external/cloudflare:
#   - email
#   - api_token
#   - account_id

# Dex
- path: dex/grafana
  data:
    - key: client_secret
      length: 32
      special: false

# Trow
- path: trow/admin
  data:
    - key: password
      length: 32
      special: true

# Matrix
- path: matrix/bot/alert
  data:
    - key: password
      length: 32
      special: true

# Matrix appservices
- path: matrix/appservice/impersonation
  data:
    - key: shared_secret
      length: 128
      special: true

- path: matrix/appservice/mautrix-whatsapp/registration
  data:
    - key: hs_token
      length: 64
      special: false
    - key: as_token
      length: 64
      special: false
    - key: provisioning_shared_secret
      length: 64
      special: false

- path: matrix/appservice/mautrix-discord/registration
  data:
    - key: hs_token
      length: 64
      special: false
    - key: as_token
      length: 64
      special: false
    - key: provisioning_shared_secret
      length: 64
      special: false
