apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ansible-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: /metal/ssh
        property: private_key
