apiVersion: v2
name: elementweb
version: 0.0.0
dependencies:
  - name: elementweb
    version: 0.0.3
    repository: https://locmai.github.io/charts # TODO switch to official chart
  - name: dendrite
    version: 5.0.0
    repository: https://k8s-at-home.com/charts/ # TODO switch to official chart
