synapse:
  serverName: "johnson.gg"
  publicServerName: "matrix.johnson.gg"

  signingkey:
    job:
      enabled: false

    existingSecret: homeserver-keys
    existingSecretKey: signing-key

  config:
    publicBaseurl: "https://matrix.johnson.gg"

    enableRegistration: false

  extraConfig:
    dynamic_thumbnails: true

    experimental_features:
      msc2716_enabled: true

    email:
      smtp_host: "smtp.smtp"
      enable_tls: false
      notif_from: "%(app)s <matrix@johnson.computer>"
      enable_notifs: true
      client_base_url: "https://chat.johnson.gg"
      invite_client_location: "https://app.element.io"

    app_service_config_files:
      - /run/appservice-mautrix-whatsapp.yaml

  synapse:
    extraVolumes:
      - name: extra-secret-config
        secret:
          secretName: extra-secret-config
      - name: whatsapp-mautrix-registration
        secret:
          secretName: matrix-mautrix-whatsapp-rendered-config
    extraVolumeMounts:
      - name: extra-secret-config
        mountPath: /synapse/config/conf.d/extra-secret-config.yaml
        subPath: config.yaml
      - name: whatsapp-mautrix-registration
        mountPath: /run/appservice-mautrix-whatsapp.yaml
        subPath: registration.yaml
    strategy:
      type: Recreate

  workers:
    default:
      strategy:
        type: Recreate

    synchrotron:
      enabled: true
      generic: true
      listeners: [client]
      csPaths:
        - "/_matrix/client/(v2_alpha|r0|v3)/sync"
        - "/_matrix/client/(api/v1|v2_alpha|r0|v3)/events"
        - "/_matrix/client/(api/v1|r0|v3)/initialSync"
        - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync"

    federation_reader:
      enabled: true
      generic: true
      listeners: [federation]
      paths:
        - "/_matrix/federation/v1/send/"

    federation_sender:
      strategy:
        type: RollingUpdate

      enabled: true

    appservice:
      enabled: true

    media_repository:
      enabled: true

  wellknown:
    enabled: true

    server:
      m.server: matrix.johnson.gg:443

    client:
      m.homeserver:
        base_url: "https://matrix.johnson.gg"

  externalPostgresql:
    host: "shared-cluster.postgresql"
    database: synapse
    username: matrix.synapse
    existingSecret: "matrix.synapse.shared-cluster.credentials.postgresql.acid.zalan.do"
    existingSecretPasswordKey: password

    sslmode: require

  persistence:
    enabled: true

    accessMode: ReadWriteMany
    size: 64Gi

  ingress:
    enabled: true
    includeServerName: false
    includeUnderscoreSynapse: false

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: "false"

    wkHosts: ["johnson.gg"]
    csHosts: ["matrix.johnson.gg"]
    hosts: ["matrix.johnson.gg"]

    tls:
      - secretName: matrix-tls-certificate
        hosts:
          - matrix.johnson.gg
          - johnson.gg

  postgresql:
    enabled: false

mautrix-whatsapp:
  senderLocalPart: FwH2K76InXpvgGnyr2r368ITzLDj3BSK

  config:
    homeserver:
      address: https://matrix.johnson.gg
      domain: johnson.gg

    appservice:
      address: http://matrix-mautrix-whatsapp.matrix.svc.cluster.local:29318

      ephemeral_events: true

    bridge:
      personal_filtering_spaces: true
      identity_change_notices: true
      private_chat_portal_meta: true
      disappearing_messages_in_groups: true
      url_previews: true

      permissions:
        "johnson.gg": user
        "@michael:johnson.gg": admin

      history_sync:
        backfill: true
        request_full_sync: true

      encryption:
        allow: true
        default: true
        require: true
        allow_key_sharing: true

        verification_levels:
          receive: cross-signed-tofu
          send: cross-signed-tofu

    logging:
      file_name_format: null
      print_level: debug
