# todo: macaroon secret key

synapse:
  serverName: "johnson.gg"
  publicServerName: "matrix.johnson.gg"

  signingKey:
    job:
      enabled: false

    existingSecret: homeserver-keys
    existingSecretKey: signing-key

  config:
    publicBaseurl: "https://matrix.johnson.gg"

    enableRegistration: false

  extraConfig:
    dynamic_thumbnails: true

  synapse:
    extraVolumes:
      - name: extra-secret-config
        secret:
          secretName: extra-secret-config
    extraVolumeMounts:
      - name: extra-secret-config
        mountPath: /run/synapse-extra-secret-config
    extraCommands:
      - "cp -av /run/synapse-extra-secret-config/config.yaml /synapse/config/conf.d/extra-secret-config.yaml"

  wellknown:
    enabled: true

    server:
      m.server: matrix.johnson.gg:443

    client:
      m.homeserver:
        base_url: "https://matrix.johnson.gg"

  postgresql:
    enabled: true
    persistence:
      enabled: false

  persistence:
    enabled: false

  ingress:
    enabled: true
    includeServerName: false

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: "false"

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8

    wkHosts: ["johnson.gg"]
    csHosts: ["matrix.johnson.gg"]
    hosts: ["matrix.johnson.gg"]

    tls:
      - secretName: matrix-tls-certificate
        hosts:
          - matrix.johnson.gg
          - johnson.gg
