dendrite:
  dendrite:
    global:
      server_name: &server_name johnson.gg
      well_known_server_name: *server_name

      presence:
        enable_inbound: true
        enable_outbound: true

      metrics:
        enabled: true

      disable_federation: true

    matrix_key_secret:
      existingSecret: homeserver-keys

    tls_secret:
      existingSecret: apex-tls-certificate

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "false"

        # only allow internal clients
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
      hosts:
        - host: *server_name
          paths:
            - path: /_matrix
              pathType: Prefix
            - path: /.well-known/matrix/server
              pathType: Exact
      tls:
        - secretName: apex-tls-certificate
          hosts:
            - *server_name

  federationapi:
    config:
      prefer_direct_fetch: true

  mediaapi:
    config:
      dynamic_thumbnails: true

  persistence:
    media:
      enabled: true
      capacity: 64Gi
    jetstream:
      enabled: true

  postgresql:
    enabled: false
    auth:
      username: dendrite
      password: cae5joov3Egh5tohwo4sunahyefe0foo5Hiengiey7rik0thaeNg3eihi0zoopoo
