elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Chat
      hajimari.io/icon: chat

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    hosts:
      - host: &host matrix.johnson.gg
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: matrix-tls-certificate
        hosts:
          - *host
  config:
    default:
      base_url: https://matrix.johnson.gg
      server_name: &server_name johnson.gg

dendrite:
  dendrite:
    global:
      server_name: *server_name
      well_known_server_name: *host

      presence:
        enable_inbound: true
        enable_outbound: true

      metrics:
        enabled: true

      disable_federation: true

    matrix_key_secret:
      existingSecret: homeserver-keys

    tls_secret:
      existingSecret: matrix-tls-certificate

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "false"

        # only allow internal clients
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
      hosts:
        - host: *host
          paths:
            - path: /_matrix
              pathType: Prefix
      tls:
        - secretName: matrix-tls-certificate
          hosts:
            - *host

  federationapi:
    config:
      prefer_direct_fetch: true

  mediaapi:
    config:
      dynamic_thumbnails: true

  persistence:
    media:
      enabled: true
      capacity: 64Gi
    jetstream:
      enabled: true

  postgresql:
    fullnameOverride: "matrix-dendrite-postgresql"

    enabled: true
    persistence:
      enabled: true
      storageClass: zfs-postgresql
