elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Chat
      hajimari.io/icon: chat

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    hosts:
      - host: &host matrix.johnson.gg
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: matrix-tls-certificate
        hosts:
          - *host
  config:
    default:
      base_url: https://matrix.johnson.gg
      server_name: *server_name

dendrite:
  dendrite:
    global:
      server_name: &server_name johnson.gg
      well_known_server_name: *host

      presence:
        enable_inbound: true
        enable_outbound: true

      metrics:
        enabled: true

      disable_federation: true

    tls_secret:
      existingSecret: matrix-tls-certificate

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "false"

        # only allow internal clients
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: matrix-tls-certificate
          hosts:
            - *host

  federationapi:
    config:
      prefer_direct_fetch: true

  mediaapi:
    config:
      dynamic_thumbnails: true

  persistence:
    media:
      enabled: true
      capacity: 64Gi
    jetstream:
      enabled: true

  postgresql:
    enabled: true
    persistence:
      enabled: true
      storageClass: zfs-postgresql

  nats:
    enabled: true

  # components:
  #   clientapi:
  #     registration:
  #       disabled: true

  #   mediaapi:
  #     dynamic_thumbnails: true

  # nats:
  #   enabled: true
  #   nats:
  #     jetstream:
  #       enabled: true

  # postgresql:
  #   enabled: false
  #   global:
  #     postgresql:
  #       postgresqlDatabase: dendrite
  #       postgresqlUsername: dendrite
  #       postgresqlPassword: dendrite
  #   persistence:
  #     enabled: true
  #     storageClass: zfs-postgresql
  #     accessModes:
  #       - ReadWriteOnce
  #     size: 5Gi

  # ingress:
  #   enabled: true
  #   className: nginx
  #   annotations:
  #     cert-manager.io/cluster-issuer: letsencrypt-prod
  #     nginx.ingress.kubernetes.io/proxy-body-size: 1g
  #     hajimari.io/enable: "false"
  #     external-dns.alpha.kubernetes.io/target: ""
  #     external-dns.alpha.kubernetes.io/cloudflare-proxied: ""
  #   hosts:
  #     - host: *host
  #       paths:
  #         - path: /_matrix
  #           pathType: Prefix
  #   tls:
  #     - secretName: dendrite-tls-certificate
  #       hosts:
  #         - *host
