synapse:
  serverName: "johnson.gg"
  publicServerName: "matrix.johnson.gg"

  signingkey:
    job:
      enabled: false

    existingSecret: homeserver-keys
    existingSecretKey: signing-key

  config:
    publicBaseurl: "https://matrix.johnson.gg"

    enableRegistration: false
    registrationSharedSecret: "overridden in secret config"

  extraConfig:
    max_upload_size: &max_size 60M

    dynamic_thumbnails: true

    url_preview_enabled: true
    url_preview_ip_range_blacklist:
      - "127.0.0.0/8"
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
      - "100.64.0.0/10"
      - "192.0.0.0/24"
      - "169.254.0.0/16"
      - "192.88.99.0/24"
      - "198.18.0.0/15"
      - "192.0.2.0/24"
      - "198.51.100.0/24"
      - "203.0.113.0/24"
      - "224.0.0.0/4"
      - "::1/128"
      - "fe80::/10"
      - "fc00::/7"
      - "2001:db8::/32"
      - "ff00::/8"
      - "fec0::/10"

    experimental_features:
      msc2716_enabled: true

    email:
      smtp_host: "smtp.smtp"
      enable_tls: false
      notif_from: "%(app)s <matrix@johnson.computer>"
      enable_notifs: true
      client_base_url: "https://chat.johnson.gg"
      invite_client_location: "https://app.element.io"

    rc_joins:
      local:
        per_second: 0.2
        burst_count: 10

    app_service_config_files:
      - /run/appservice-mautrix-whatsapp.yaml
      - /run/appservice-mautrix-discord.yaml

  synapse:
    extraVolumes:
      - name: shared-secret-authenticator
        configMap:
          name: shared-secret-authenticator
      - name: extra-secret-config
        secret:
          secretName: extra-secret-config
      - name: mautrix-whatsapp-registration
        secret:
          secretName: matrix-mautrix-whatsapp-rendered-config
      - name: mautrix-discord-registration
        secret:
          secretName: matrix-mautrix-discord-rendered-config
    extraVolumeMounts:
      - name: shared-secret-authenticator
        mountPath: /usr/local/lib/python3.9/site-packages/shared_secret_authenticator.py
        subPath: shared_secret_authenticator.py
      - name: extra-secret-config
        mountPath: /synapse/config/conf.d/extra-secret-config.yaml
        subPath: config.yaml
      - name: mautrix-whatsapp-registration
        mountPath: /run/appservice-mautrix-whatsapp.yaml
        subPath: registration.yaml
      - name: mautrix-discord-registration
        mountPath: /run/appservice-mautrix-discord.yaml
        subPath: registration.yaml
    strategy:
      type: Recreate

  workers:
    default:
      strategy:
        type: Recreate

      volumes:
        - name: shared-secret-authenticator
          configMap:
            name: shared-secret-authenticator
        - name: extra-secret-config
          secret:
            secretName: extra-secret-config
        - name: mautrix-whatsapp-registration
          secret:
            secretName: matrix-mautrix-whatsapp-rendered-config
        - name: mautrix-discord-registration
          secret:
            secretName: matrix-mautrix-discord-rendered-config
      volumeMounts:
        - name: shared-secret-authenticator
          mountPath: /usr/local/lib/python3.9/site-packages/shared_secret_authenticator.py
          subPath: shared_secret_authenticator.py
        - name: extra-secret-config
          mountPath: /synapse/config/conf.d/extra-secret-config.yaml
          subPath: config.yaml
        - name: mautrix-whatsapp-registration
          mountPath: /run/appservice-mautrix-whatsapp.yaml
          subPath: registration.yaml
        - name: mautrix-discord-registration
          mountPath: /run/appservice-mautrix-discord.yaml
          subPath: registration.yaml

    synchrotron:
      enabled: true
      generic: true
      listeners: [client]
      csPaths:
        - "/_matrix/client/(v2_alpha|r0|v3)/sync"
        - "/_matrix/client/(api/v1|v2_alpha|r0|v3)/events"
        - "/_matrix/client/(api/v1|r0|v3)/initialSync"
        - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync"

    federation_reader:
      enabled: true
      generic: true
      listeners: [federation]
      paths:
        - "/_matrix/federation/v1/send/"

    federation_sender:
      strategy:
        type: RollingUpdate

      enabled: true

    appservice:
      enabled: true

    media_repository:
      enabled: true

  wellknown:
    enabled: true

    server:
      m.server: matrix.johnson.gg:443

    client:
      m.homeserver:
        base_url: "https://matrix.johnson.gg"

  externalPostgresql:
    host: "shared-cluster.postgresql"
    database: synapse
    username: matrix.synapse
    existingSecret: "matrix.synapse.shared-cluster.credentials.postgresql.acid.zalan.do"
    existingSecretPasswordKey: password

    sslmode: require

  persistence:
    enabled: true

    accessMode: ReadWriteMany
    size: 64Gi

  ingress:
    enabled: true
    includeServerName: false
    includeUnderscoreSynapse: true

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: *max_size
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

    wkHosts: ["johnson.gg"]
    csHosts: ["matrix.johnson.gg"]
    hosts: ["matrix.johnson.gg"]

    tls:
      - secretName: matrix-tls-certificate
        hosts:
          - matrix.johnson.gg
          - johnson.gg

  postgresql:
    enabled: false

mautrix-whatsapp:
  senderLocalPart: FwH2K76InXpvgGnyr2r368ITzLDj3BSK

  config:
    homeserver:
      address: https://matrix.johnson.gg
      domain: johnson.gg

    appservice:
      address: http://matrix-mautrix-whatsapp.matrix.svc.cluster.local:29318

      ephemeral_events: true

    bridge:
      personal_filtering_spaces: true
      identity_change_notices: true
      private_chat_portal_meta: true
      disappearing_messages_in_groups: true
      url_previews: true

      permissions:
        "johnson.gg": user
        "@michael:johnson.gg": admin

      history_sync:
        backfill: true
        request_full_sync: true

      encryption:
        allow: true
        default: true
        require: true
        allow_key_sharing: true

        verification_levels:
          receive: cross-signed-tofu
          send: cross-signed-tofu
          share: cross-signed-tofu

    logging:
      file_name_format: null
      print_level: info

mautrix-discord:
  senderLocalPart: b4aDftoUvQCiK7Fxonb4VgRLYfVKcjgY

  config:
    homeserver:
      address: https://matrix.johnson.gg
      domain: johnson.gg

    appservice:
      address: http://matrix-mautrix-discord.matrix.svc.cluster.local:29334

      ephemeral_events: true

    bridge:
      private_chat_portal_meta: true
      delivery_receipts: true

      encryption:
        allow: true
        default: false
        require: false
        allow_key_sharing: true

        verification_levels:
          receive: cross-signed-tofu
          send: cross-signed-tofu
          share: cross-signed-tofu

      permissions:
        "johnson.gg": user
        "@michael:johnson.gg": admin

    logging:
      file_name_format: null
      print_level: info
