dendrite:
  dendrite:
    polylithEnabled: true

    global:
      server_name: &server_name johnson.gg
      well_known_server_name: *server_name

      presence:
        enable_inbound: true
        enable_outbound: true

      metrics:
        enabled: true

      disable_federation: true

    matrix_key_secret:
      existingSecret: homeserver-keys

    tls_secret:
      existingSecret: apex-tls-certificate

  ingress:
    main:
      enabled: false

  clientapi:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: "false"

          # only allow internal clients
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
        hosts:
          - host: *server_name
            paths:
              - path: /_matrix/client
                pathType: Prefix
        tls:
          - secretName: apex-tls-certificate
            hosts:
              - *server_name

  federationapi:
    config:
      prefer_direct_fetch: true

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: "false"

          # only allow internal clients
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
        hosts:
          - host: *server_name
            paths:
              - path: /_matrix/federation
                pathType: Prefix
              - path: /_matrix/key
                pathType: Prefix
        tls:
          - secretName: apex-tls-certificate
            hosts:
              - *server_name

  mediaapi:
    config:
      dynamic_thumbnails: true

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: "false"

          # only allow internal clients
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
        hosts:
          - host: *server_name
            paths:
              - path: /_matrix/media
                pathType: Prefix
        tls:
          - secretName: apex-tls-certificate
            hosts:
              - *server_name

  syncapi:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/use-regex: "true"

          # only allow internal clients
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
        hosts:
          - host: *server_name
            paths:
              - path: "/_matrix/client/.*?/(sync|user/.*?/filter/?.*|keys/changes|rooms/.*?/messages)$"
                pathType: Prefix
        tls:
          - secretName: apex-tls-certificate
            hosts:
              - *server_name

  persistence:
    media:
      enabled: true
      capacity: 64Gi
    jetstream:
      enabled: true

  postgresql:
    fullnameOverride: "matrix-dendrite-postgresql"

    enabled: true
    persistence:
      enabled: true
      storageClass: zfs-postgresql

  nats:
    enabled: true
    nameOverride: dendrite-nats
