authentik:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Authentik
      hajimari.io/icon: shield-account

      # only allow internal clients
      nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    hosts:
      - host: &host login.johnson.computer
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: authentik-tls-certificate
        hosts:
          - *host

  authentik:
    email:
      host: smtp.smtp
      port: 25
      from: "Authentik <authentik@johnson.computer>"

    postgresql:
      host: postgresql.postgresql.svc.cluster.local

  envFrom:
    - secretRef:
        name: authentik-secret-env
      prefix: "AUTHENTIK_"
    - secretRef:
        name: authentik-secret-env
      prefix: "AUTHENTIK_"

  env:
    AUTHENTIK_POSTGRESQL__NAME: authentik

  envValueFrom:
    AUTHENTIK_POSTGRESQL__USER:
      secretKeyRef:
        name: authentik.authentik.shared-cluster.credentials.postgresql.acid.zalan.do
        key: username
    AUTHENTIK_POSTGRESQL__PASSWORD:
      secretKeyRef:
        name: authentik.authentik.shared-cluster.credentials.postgresql.acid.zalan.do
        key: password

  prometheus:
    serviceMonitor:
      create: true
    rules:
      create: true

  redis:
    enabled: true
