ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: "Local"

    ingressClassResource:
      default: true

    admissionWebhooks:
      timeoutSeconds: 30

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
