ingress-nginx:
  controller:
    replicaCount: 2

    service:
      sessionAffinity: ClientIP

    ingressClassResource:
      default: true

    admissionWebhooks:
      timeoutSeconds: 30

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    6789: unifi/unifi:6789

  udp:
    3478: unifi/unifi:3478
