apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: smtp-secrets
  data:
    - secretKey: MAILNAME
      remoteRef:
        key: /smtp/config
        property: mailname
    - secretKey: RELAY_NETWORKS
      remoteRef:
        key: /smtp/config
        property: relay-networks
    - secretKey: SES_USER
      remoteRef:
        key: /smtp/aws-ses
        property: username
    - secretKey: SES_PASSWORD
      remoteRef:
        key: /smtp/aws-ses
        property: password
