apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: smtp-credentials
  data:
    - secretKey: RELAYHOST_USERNAME
      remoteRef:
        key: /smtp/aws-ses
        property: username
    - secretKey: RELAYHOST_PASSWORD
      remoteRef:
        key: /smtp/aws-ses
        property: password
